/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAlbumDialog: typeof import('./components/dialogs/AddAlbumDialog.vue')['default']
    AddUserDialog: typeof import('./components/dialogs/AddUserDialog.vue')['default']
    AlbumCard: typeof import('./components/AlbumCard.vue')['default']
    AlbumComponent: typeof import('./components/AlbumComponent.vue')['default']
    AlbumGallery: typeof import('./components/AlbumGallery.vue')['default']
    AmbientVideoPlayer: typeof import('./components/AmbientVideoPlayer.vue')['default']
    ConfirmDialog: typeof import('./components/dialogs/ConfirmDialog.vue')['default']
    ImageCard: typeof import('./components/ImageCard.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    ImageHeatmapChart: typeof import('./components/charts/ImageHeatmapChart.vue')['default']
    LoginDialog: typeof import('./components/dialogs/LoginDialog.vue')['default']
    MultiLocationMap: typeof import('./components/MultiLocationMap.vue')['default']
    Page403: typeof import('./components/error/Page403.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleLocationMap: typeof import('./components/SingleLocationMap.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
    UploadDialog: typeof import('./components/dialogs/UploadDialog.vue')['default']
    UploadWidget: typeof import('./components/UploadWidget.vue')['default']
    UserList: typeof import('./components/lists/UserList.vue')['default']
    WelcomeComponent: typeof import('./components/WelcomeComponent.vue')['default']
  }
}
