/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/album/': RouteRecordInfo<'/album/', '/album', Record<never, never>, Record<never, never>>,
    '/album/[id]': RouteRecordInfo<'/album/[id]', '/album/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/favorites/': RouteRecordInfo<'/favorites/', '/favorites', Record<never, never>, Record<never, never>>,
    '/image/[id]': RouteRecordInfo<'/image/[id]', '/image/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/image-stream/': RouteRecordInfo<'/image-stream/', '/image-stream', Record<never, never>, Record<never, never>>,
    '/map/': RouteRecordInfo<'/map/', '/map', Record<never, never>, Record<never, never>>,
    '/search/[search]': RouteRecordInfo<'/search/[search]', '/search/:search', { search: ParamValue<true> }, { search: ParamValue<false> }>,
    '/statistics/': RouteRecordInfo<'/statistics/', '/statistics', Record<never, never>, Record<never, never>>,
    '/tag/': RouteRecordInfo<'/tag/', '/tag', Record<never, never>, Record<never, never>>,
    '/tag/[id]': RouteRecordInfo<'/tag/[id]', '/tag/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }
}
